### ISSUE TITLE
volatile 讨论

### ISSUE THREAD

**Issue by Harlber** [BeesAndroid/BeesAndroid#10]
位置：[Android系统设计原则与设计模式](https://github.com/BeesAndroid/BeesAndroid/blob/master/doc/Android%E7%B3%BB%E7%BB%9F%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99%E4%B8%8E%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.md)

单例模式中的volatile，一般使用于jdk1.5后

**Comment by liangsaifei** [comment]
有不同意见，可以fork 然后pr

**Comment by Harlber** [comment]
这点东西就不需要了吧，知道下就ok

**Comment by guoxiaoxing** [comment]
篇幅限制，有些东西没有写的特别细致，包括不同Android版本、不同JDK版本的区别。

**Comment by Harlber** [comment]
辛苦

**Comment by Harlber** [comment]
DCL 相关  http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
