### ISSUE TITLE
Android虚拟机框架：Java类加载机制                图片资源缺失

### ISSUE THREAD

**Issue by MartinLi2015** [BeesAndroid/BeesAndroid#4]
## 文章描述

文章标题：Android虚拟机框架：Java类加载机制

文章链接：https://github.com/BeesAndroid/BeesAndroid/blob/master/doc/%E5%8E%9F%E7%90%86%E7%AF%87/%E8%BF%90%E8%A1%8C%E6%97%B6%E5%B1%82/JVM%E8%99%9A%E6%8B%9F%E6%9C%BA/01Android%E8%99%9A%E6%8B%9F%E6%9C%BA%E6%A1%86%E6%9E%B6%EF%BC%9AJava%E7%B1%BB%E5%8A%A0%E8%BD%BD%E6%9C%BA%E5%88%B6.md

### 文章中有什么问题？
  图片资源丢失

### 你觉得这些问题可以如何解决，你的建议是什么？
更新资源链接

**Comment by guoxiaoxing** [comment]
不要急哈，这些文章都在重新修改校对中，最新校对好的文章以repo首页发出来的为准。

**Comment by guoxiaoxing** [comment]
因为是从https://github.com/guoxiaoxing/android-open-source-project-analysis迁移过来的，所以想乘这这次机会对文章进行重新校对。
