### ISSUE TITLE
图片缺失加载不出来

### ISSUE THREAD

**Issue by zktzktzkt** [BeesAndroid/BeesAndroid#8]
## 文章描述

文章标题：  Android视图系统：Android应用视图管理者Window

文章链接：https://github.com/BeesAndroid/BeesAndroid/blob/master/doc/%E5%8E%9F%E7%90%86%E7%AF%87/%E5%BA%94%E7%94%A8%E6%A1%86%E6%9E%B6%E5%B1%82/Android%E8%A7%86%E5%9B%BE%E7%B3%BB%E7%BB%9F/Android%E8%A7%86%E5%9B%BE%E7%B3%BB%E7%BB%9F%EF%BC%9AAndroid%E5%BA%94%E7%94%A8%E8%A7%86%E5%9B%BE%E7%AE%A1%E7%90%86%E8%80%85Window.md

**Comment by guoxiaoxing** [comment]
文章校对中，可以先查阅以前的repo：https://github.com/guoxiaoxing/android-open-source-project-analysis

**Comment by zktzktzkt** [comment]
多句嘴哈，平时用什么时间来写这些文章？又是基于什么动力让你做这件事？

**Comment by guoxiaoxing** [comment]
周末，下班后，或者在公司没需求的时候，老大也支持我们做这些事情。自我学习，文章的出发点也是总结给自己看的。
